import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Card from "@/components/card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const handleOnBannerBtnClick = () => {
		console.log("Hi You Clicked Button");
	};
	return (
		<>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Banner
					buttonText="Veiw Stores nearby"
					handleOnClick={handleOnBannerBtnClick}
				/>
				<div className={styles.heroImage}>
					<Image src="/Static/Coffee.png" width={210} height={190}></Image>
				</div>
				<Card
					name="Kay Coffee"
					imgUrl="/Static/mega-creator.png"
					href="coffee-store/kay-coffee"
				/>
			</main>
			{/* <footer className={styles.footer}></footer> */}
		</>
	);
}
